### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RyanMilb** [Satoshis-Games/Games#1]
In Flappy Crypto/README.md

Line 5 has a broken link it should be updated to this:
https://satoshis.games/flappycrypto/index.htm

**Comment by CarlosRoldanx** [comment]
Hey @RyanMilb 

Sorry for the late response. We are using Keybase Git for the latest release and then we will update GitHub with the stable release. I will fix it. Feel free to submit a PR 👍  :)

**Comment by whiteyhat** [comment]
Thanks @RyanMilb 

Fixed!
